app_config:
    # Overview
    package_name: "model-training"
    
    # Training data
    training_data: "/data/training.csv"

    # pipeline_save_file: "logistic_regression_output_v"
    pipeline_save_file: "random_forest_output_v"

    predict_path: "/data/public_processed.csv"
    
log_config:
    target: "label"

    used_model: 'random_forest'
    
    samples_to_train_ratio: 0.01
    
    # not used features
    to_drop:
        - "txkey"
        - "chid"
        - "cano"
        - "mchno"
        - "acqic"
        - "contp"
        - "bnsfg"
        - "flam1"
        - "stocn"
        - "stscd"
        - "flbmk"
        - "hcefg"
        - "flg_3dsmk"
 
    
    # For train test split
    random_state: 42
    test_size: 0.1

    vars_with_na:
        - "etymd"
        - "mcc"
        - "scity"
        - "csmcu"

    time_transform: "loctm"

    features:
        - "etymd"
        - "mcc"
        - "ecfg"
        - "scity"
        - "ovrlt"
        - "csmcu"
        - "locdt" 
        - "loctm"
        - "conam"
        - "iterm"
        - "csmam"
        
    use_sampling: True
    
    # smote hyperparameters
    smote:
        sampling_strategy: 0.5
        k_neighbors: 3
        

    # logistic hyperparameters
    logistic:
        max_iter: 5000
        solver: "saga"
        n_jobs: -1

    # random forest hyperparameters
    random_forest:
        bootstrap: True
        random_state: 42
        class_weight: 
            0: 1
            1: 2
        n_jobs: -1
        # class_weight: 
        #     0: 0.37
        #     1: 99.63
    xgb:
        objective: "binary:logistic"
        random_state: 42
        scale_pos_weight: 2

    
cv_config:
    stratifiedkfold:
        n_splits: 5
        shuffle: True
        random_state: 42
    random_forest:
        random_forest__criterion: 
            - 'gini'
            - 'entropy'
            - 'log_loss'
        random_forest__n_estimators: 
            - 50
            - 100
            - 200
        random_forest__max_depth: 
            - 
            - 10 
            - 20
        
    
mlflow_config:
    experiment_name: 'random forest_with_SMOTE'

    experiment_tags:
        project_name: 'detect credit card fraud'
        mlflow.note/content: 'This is the experiment for random forest'
        
        
    

