channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.3.1
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - imbalanced-learn==0.11.0
  - numpy==1.24.0
  - packaging==23.1
  - pandas==1.5.3
  - psutil==5.9.6
  - pydantic==1.10.13
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
  - strictyaml==1.7.3
  - xgboost==2.0.1
name: mlflow-env