app_config:
    # Overview
    package_name: "logistic"
    
    # Training data
    training_data: "/data/training.csv"

    pipeline_save_file: "logistic_regression_output_v"
    
log_config:
    target: "label"

    samples_to_train_ratio: 0.99
    
    # not used features
    to_drop:
        - "txkey"
        - "chid"
        - "cano"
        - "mchno"
        - "acqic"
        - "contp"
        - "bnsfg"
        - "flam1"
        - "stocn"
        - "stscd"
        - "flbmk"
        - "hcefg"
        - "flg_3dsmk"
 
    
    # For train test split
    random_state: 42
    test_size: 0.01

    vars_with_na:
        - "etymd"
        - "mcc"
        - "scity"
        - "csmcu"

    time_transform: "loctm"

    features:
        - "etymd"
        - "mcc"
        - "ecfg"
        - "scity"
        - "ovrlt"
        - "csmcu"
        - "locdt" 
        - "loctm"
        - "conam"
        - "iterm"
        - "csmam"

    
    # smote hyperparameters
    smote:
        sampling_strategy: 0.5
        k_neighbors: 3
        

    # logistic hyperparameters
    logistic:
        max_iter: 5000
        solver: "saga"
        n_jobs: -1

mlflow_config:
    experiment_name: 'logistic_with_SMOTE'

    experiment_tags:
        project_name: 'detect credit card fraud'
        mlflow.note/content: 'This is the experiment for logistic regression'
        
        
    

